site_name: uwouni
site_url: https://www.uwouni.com/

nav:
  - 首页: index.md
  - 微积分:
    - 第 0 章 预备知识: blog/微积分/0.md
    - 第一章 函数与极限: blog/微积分/1.md
    - 第二章 导数与微分: blog/微积分/2.md
    - 第三章 微分中值定理及导数的应用: blog/微积分/3.md
    - 期中复习: blog/微积分/期中复习.md
    - 第四章 不定积分: blog/微积分/4.md
    - 第五章 定积分及其应用: blog/微积分/5.md
    - 期末复习: blog/微积分/期末复习.md
  - 线性代数:
    - 第一章 线性方程组的求解: blog/线性代数/1.md
    - 第二章 行列式与矩阵的秩: blog/线性代数/2.md
    - 第三章 矩阵的运算: blog/线性代数/3.md
    - 第四章 $n$ 元向量空间: blog/线性代数/4.md
    - 期中复习: blog/线性代数/期中复习.md
    - 第七章 线性空间: blog/线性代数/7.md
    - 第八章 欧式空间: blog/线性代数/8.md
    - 第五章 矩阵的特征值理论与相似对角化: blog/线性代数/5.md
    - 第六章 二次型: blog/线性代数/6.md
    - 期末复习: blog/线性代数/期末复习.md
  - C 程:
    - 知识碎屑: blog/C 程/知识碎屑.md
    - 指针: blog/C 程/指针.md
    - 文件: blog/C 程/文件.md
    - 踩过的坑: blog/C 程/踩过的坑.md
    - 期末复习: blog/C 程/期末复习.md
  - 大一秋冬:
    - info: blog/大一秋冬/index.md
    - 大英三:
      - to do: blog/大一秋冬/大英三/to do.md
      - B1U1-4: blog/大一秋冬/大英三/B1U1-4.md
      - B2U1 Mind the gap: blog/大一秋冬/大英三/B2U1.md
      - B2U2 On the road: blog/大一秋冬/大英三/B2U2.md
      - B2U3 Just relax!: blog/大一秋冬/大英三/B2U3.md
      - B2U4 Does gender matter?: blog/大一秋冬/大英三/B2U4.md
      - Quiz1 复习: blog/大一秋冬/大英三/Quiz1.md
      - B2U5 The power of words: blog/大一秋冬/大英三/B2U5.md
      - B2U6 You are what you eat: blog/大一秋冬/大英三/B2U6.md
      - B2U7 Nature's gifts: blog/大一秋冬/大英三/B2U7.md
      - B2U8 Technology:controllers or helpers?: blog/大一秋冬/大英三/B2U8.md
      - Quiz2 复习: blog/大一秋冬/大英三/Quiz2.md
      - Oral exam 准备: blog/大一秋冬/大英三/Oral.md
      - Read 准备: blog/大一秋冬/大英三/Read.md
      - 期末复习: blog/大一秋冬/大英三/Final.md
    - 汇编基础:
      - info: blog/大一秋冬/汇编基础/0.md
      - 环境配置: blog/大一秋冬/汇编基础/1.md
      - 汇编入门: blog/大一秋冬/汇编基础/2.md
      - 做题记录: blog/大一秋冬/汇编基础/solve.md
      - 期末复习: blog/大一秋冬/汇编基础/期末复习.md
    - 无线网络应用:
      - info: blog/大一秋冬/无线网络应用/0.md
      - 资料搜集: blog/大一秋冬/无线网络应用/资料搜集.md
      - 模块 1：当今网络: blog/大一秋冬/无线网络应用/1.md
      - 模块 3：协议和模型: blog/大一秋冬/无线网络应用/3.md
      - 模块 5-9：数值系统 数据链路 以太网交换 网络层 地址解析: blog/大一秋冬/无线网络应用/5-9.md
      - 模块 4：物理层: blog/大一秋冬/无线网络应用/4.md
      - 模块 11-12：IPv4 和 IPv6: blog/大一秋冬/无线网络应用/11-12.md
      - (为实验补充介绍) 无线技术: blog/大一秋冬/无线网络应用/00.md
      - 实验二：无线路由器与 AP 配置应用: blog/大一秋冬/无线网络应用/实验二.md
      - 模块 2,10：交换机 路由器 终端设备 基本配置: blog/大一秋冬/无线网络应用/2,10.md
      - 模块 14-15：传输层 应用层: blog/大一秋冬/无线网络应用/14-15.md
      - 实验三：无线网络 DNS IIS 服务配置应用: blog/大一秋冬/无线网络应用/实验三.md
      - 模块 16：网络安全基础知识: blog/大一秋冬/无线网络应用/16.md
      - (为实验补充介绍) 无线网络安全性: blog/大一秋冬/无线网络应用/01.md
      - 模块 17：构建小型网络: blog/大一秋冬/无线网络应用/17.md
      - 模块 13：ICMP: blog/大一秋冬/无线网络应用/13.md
      - 实验四：防火墙等无线网络安全实验: blog/大一秋冬/无线网络应用/实验四.md
      - 实验五：无线网络 DHCP 服务及 AP 组网: blog/大一秋冬/无线网络应用/实验五.md
      - 实验六：无线流媒体服务及虚拟 WiFi 组网: blog/大一秋冬/无线网络应用/实验六.md
      - 在线学习心得: blog/大一秋冬/无线网络应用/在线学习心得.md
theme:
  name: material
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: 'https://cdn.luogu.com.cn/upload/image_hosting/uo5wu9mh.png'
  icon:
    logo: 'material/school'
  features:
    - search
    - content.action.edit
    - navigation.tabs
    - navigation.instant
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - content.code.copy #代码复制
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share
    - navigation.tracking
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css  # KaTeX样式
  - stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js   # KaTeX核心
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js  # 自动渲染
  - javascripts/katex.js

plugins:
  - search
  - document-dates:
       position: top
       show_author: false
  # - encryptcontent:  
  #     global_password: SECRET
  #     title_prefix: ''
  #    remember_password: False 
  #    summary: '看不到我~'
  #    hljs: True
  #    mermaid2: True
  #    decryption_failure_message: '密码错误'
  #    encryption_info_message: '该笔记不对外公开'
  #    encrypted_something:
  #      md-footer__inner: [nav, class] #Footer
   #     md-nav: [nav, class] #Menu and toc
   #   inject:
   #     md-content: [div, class]
      # password_file: 'passwords.yml'

markdown_extensions: #详见https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/ 和 https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  # - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # - markdown.extensions.toc:
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  #     permalink: "\ue157"